sudo: required
dist: trusty
language: node_js
node_js:
  - '8.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm i -g @angular/cli
  - npm i -g karma
  - npm i -g angular-cli-ghpages
  - npm install
  - ng build --prod --base-href "/NoteShareWeb/"

script: karma start config/karma.conf.js --single-run

after_success:
  - ngh