sudo: required
dist: trusty
language: node_js
node_js:
  - '8.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm i -g angular-cli-ghpages

script: ng build --prod --base-href "/NoteShareWeb/"

after_success:
  - ngh --no-silent --repo=https://GH_TOKEN@github.com/SepSpring2017/NoteShareWeb.git